kind: Task
apiVersion: tekton.dev/v1alpha1
metadata:
  annotations:
    tekton.dev/pipelines.minVersion: 0.17.0
    tekton.dev/tags: image-build
  labels:
    app.kubernetes.io/version: '0.3'
  name: kaniko
  namespace: duxinyan
spec:
  description: >-
    This Task builds source into a container image using Google's kaniko tool.
    Kaniko doesn't depend on a Docker daemon and executes each command within a
    Dockerfile completely in userspace. This enables building container images
    in environments that can't easily or securely run a Docker daemon, such as a
    standard Kubernetes cluster.
  params:
    - description: myrepo/myimage.
      name: IMAGE
      type: string
    - default: latest
      description: tag of image
      name: imageTag
      type: string
    - default: ./Dockerfile
      description: Path to the Dockerfile to build.
      name: DOCKERFILE
      type: string
    - default: ./
      description: The build context used by Kaniko.
      name: CONTEXT
      type: string
    - default: ''
      name: EXTRA_ARGS
      type: string
    - default: 'r.addops.soft.360.cn/kaniko-project/executor:v1.6.0'
      description: The image on which builds will run
      name: BUILDER_IMAGE
      type: string
  results:
    - description: Digest of the image just built.
      name: IMAGE-DIGEST
  steps:
    - args:
        - $(params.EXTRA_ARGS)
        - '--dockerfile=$(params.DOCKERFILE)'
        - '--context=$(workspaces.source.path)/$(params.CONTEXT)'
        - '--destination=$(params.IMAGE):$(params.imageTag)'
        - >-
          --oci-layout-path=$(workspaces.source.path)/$(params.CONTEXT)/image-digest
      image: $(params.BUILDER_IMAGE)
      name: build-and-push
      resources: {}
      securityContext:
        runAsUser: 0
      workingDir: $(workspaces.source.path)
    - args:
        - >-
          -images=[{"name":"$(params.IMAGE)","type":"image","url":"$(params.IMAGE)","digest":"","OutputImageDir":"$(workspaces.source.path)/$(params.CONTEXT)/image-digest"}]
        - '-terminationMessagePath=$(params.CONTEXT)/image-digested'
      command:
        - /ko-app/imagedigestexporter
      image: 'r.addops.soft.360.cn/tektoncd/pipeline/cmd/imagedigestexporter:v0.24.1'
      name: write-digest
      resources: {}
      securityContext:
        runAsUser: 0
      workingDir: $(workspaces.source.path)
    - image: 'docker.io/stedolan/jq:latest'
      name: digest-to-results
      resources: {}
      script: >
        cat $(params.CONTEXT)/image-digested | jq '.[0].value' -rj | tee
        /tekton/results/IMAGE-DIGEST
      workingDir: $(workspaces.source.path)
  workspaces:
    - description: Holds the context and docker file
      name: source
    - description: Includes a docker `config.json`
      mountPath: /kaniko/.docker
      name: dockerconfig
      optional: true
