apiVersion: image.toolkit.fluxcd.io/v1alpha2
kind: ImageUpdateAutomation
metadata:
  name: demo
  namespace: dev
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: demo
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: Xinyan272@users.noreply.github.com
      messageTemplate: '{{range .Updated.Images}}{{println .}}{{end}}'
    push:
      branch: main
  update:
    path: ./deploy
    strategy: Setters