apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-echo
  labels:
    app: go-echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-echo
  template:
    metadata:
      labels:
        app: go-echo
    spec:
      containers:
        - name: go-echo
          image: r.addops.soft.360.cn/duxinyan/demo:latest # {"$imagepolicy": "dev:demo"}
          ports:
            - containerPort: 8080