kind: ConfigMap
apiVersion: v1
metadata:
  name: pipelinerun-template
  namespace: duxinyan
data:
  pipelineRunTemplate: |
    apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: demo-pipeline-
      namespace: duxinyan
      labels:
        name: git-pulling
    spec:
      serviceAccountName: pipeline-account
      resources:
        - name: git-resource
          resourceRef:
            name: kaniko-git-source
      pipelineRef:
        name: kaniko-pipeline
      workspaces:
        - name: dockerconfig
          secret:
            secretName: imageRepo-secret
      params:
        - name: IMAGE
          value: imageRepoUrl/demo/test
        - name: IMAGETAG
          value: {{ index . "SHORT_SHA" }}
        - name: DOCKERFILE
          value: ./go-echo/Dockerfile
        - name: CONTEXT
          value: ./go-echo
