kind: TriggerBinding
apiVersion: triggers.tekton.dev/v1alpha1
metadata:
  name: pipeline-binding-repo
  namespace: duxinyan
spec:
  params:
    - name: image-url
      value: imageRepoUrl/demo/test
    - name: DOCKERFILE
      value: ./go-echo/Dockerfile
    - name: CONTEXT
      value: ./go-echo