kind: TriggerTemplate
apiVersion: triggers.tekton.dev/v1alpha1
metadata:
  name: demo-pipeline-template
  namespace: duxinyan
spec:
  params:
    - description: The git repository URL to clone from.
      name: repo-url
    - default: main
      description: The git branch to clone.
      name: branch-name
    - description: The image url for git repo
      name: image-url
    - default: latest
      description: the image name
      name: image-tag
    - description: Path to the Dockerfile to build
      name: DOCKERFILE
      default: ./DOCKERFILE
    - description: The build context used by Kaniko.
      name: CONTEXT
      default: ./
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: demo-pipeline-
        namespace: duxinyan
      spec:
        params:
        - name: IMAGE
          value: $(tt.params.image-url)
        - name: IMAGETAG
          value: $(tt.params.image-tag)
        - name: DOCKERFILE
          value: $(tt.params.DOCKERFILE)
        - name: CONTEXT
          value: $(tt.params.CONTEXT)
        serviceAccountName: pipeline-account
        resources:
          - name: git-resource
            resourceSpec:
              type: git
              params:
                - name: revision
                  value: $(tt.params.branch-name)
                - name: url
                  value: $(tt.params.repo-url)
        pipelineRef:
          name: kaniko-pipeline
        workspaces:
          - name: dockerconfig
            secret:
              secretName: imageRepo-secret
