kind: Pipeline
apiVersion: tekton.dev/v1alpha1
metadata:
  name: kaniko-pipeline
  namespace: duxinyan
spec:
  params:
    - description: The image url for git repo
      name: IMAGE
      type: string
    - default: latest
      description: the image tag
      name: IMAGETAG
      type: string
    - default: ./Dockerfile
      description: Path to the Dockerfile to build
      name: DOCKERFILE
      type: string
    - default: ./
      description: The build context used by Kaniko.
      name: CONTEXT
      type: string
  resources:
    - name: git-resource
      type: git
  tasks:
    - name: kaniko
      params:
        - name: IMAGE
          value: $(params.IMAGE)
        - name: imageTag
          value: $(params.IMAGETAG)
        - name: DOCKERFILE
          value: $(params.DOCKERFILE)
        - name: CONTEXT
          value: $(params.CONTEXT)
        - name: EXTRA_ARGS
          value: '--skip-tls-verify'
      resources:
        inputs:
          - name: git-source
            resource: git-resource
      taskRef:
        kind: Task
        name: kaniko
      workspaces:
        - name: dockerconfig
          workspace: dockerconfig
    - name: verify-digest
      params:
        - name: digest
          value: $(tasks.kaniko.results.IMAGE-DIGEST)
      runAfter:
        - kaniko
      taskSpec:
        params:
          - name: digest
            type: string
        steps:
          - image: ubuntu
            name: bash
            resources: {}
            script: |
              echo $(params.digest)
              case .$(params.digest) in
                ".sha"*) exit 0 ;;
                *)       echo "Digest value is not correct" && exit 1 ;;
              esac
  workspaces:
    - description: Includes a docker `config.json`
      name: dockerconfig
